#namespace: trustyai-service-operator-system

namePrefix: trustyai-service-operator-

resources:
- ../crd
- ../rbac
- ../manager

commonLabels:
  app.kubernetes.io/part-of: trustyai

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml

configMapGenerator:
  - env: params.env
    name: config

configurations:
  - params.yaml

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: trustyaiServiceImage
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImage
  - name: trustyaiOperatorImage
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiOperatorImage