#namespace: trustyai-service-operator-system

namePrefix: trustyai-service-operator-

resources:
- ../crd
- ../rbac
- ../manager

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml

configMapGenerator:
  - env: params.env
    name: config

configurations:
  - params.yaml

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: trustyaiServiceImageName
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImageName
  - name: trustyaiServiceImageTag
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImageTag
  - name: trustyaiOperatorImageName
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiOperatorImageName
  - name: trustyaiOperatorImageTag
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiOperatorImageTag