---
namePrefix: trustyai-service-operator-

resources:
  - ../crd
  - ../rbac
  - ../manager
  - ../prometheus

commonLabels:
  app.kubernetes.io/part-of: trustyai

configMapGenerator:
  - env: params.env
    name: config

configurations:
  - params.yaml

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: trustyaiServiceImage
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImage
  - name: trustyaiOperatorImage
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiOperatorImage
  - name: kube-rbac-proxy
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.kube-rbac-proxy
  - name: kServeServerless
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.kServeServerless
