//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/trustyai-explainability/trustyai-service-operator/api/common"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuardrailPolicy) DeepCopyInto(out *ClusterGuardrailPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuardrailPolicy.
func (in *ClusterGuardrailPolicy) DeepCopy() *ClusterGuardrailPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterGuardrailPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGuardrailPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuardrailPolicyList) DeepCopyInto(out *ClusterGuardrailPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGuardrailPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuardrailPolicyList.
func (in *ClusterGuardrailPolicyList) DeepCopy() *ClusterGuardrailPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterGuardrailPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGuardrailPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuardrailPolicySpec) DeepCopyInto(out *ClusterGuardrailPolicySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(GuardrailRules)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(PolicyDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(PolicyOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuardrailPolicySpec.
func (in *ClusterGuardrailPolicySpec) DeepCopy() *ClusterGuardrailPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGuardrailPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuardrailPolicyStatus) DeepCopyInto(out *ClusterGuardrailPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]common.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NemoGuardrailsRef != nil {
		in, out := &in.NemoGuardrailsRef, &out.NemoGuardrailsRef
		*out = new(ManagedResourceRef)
		**out = **in
	}
	if in.IPPConfigRefs != nil {
		in, out := &in.IPPConfigRefs, &out.IPPConfigRefs
		*out = make([]ManagedResourceRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuardrailPolicyStatus.
func (in *ClusterGuardrailPolicyStatus) DeepCopy() *ClusterGuardrailPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGuardrailPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardPluginConfig) DeepCopyInto(out *GuardPluginConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardPluginConfig.
func (in *GuardPluginConfig) DeepCopy() *GuardPluginConfig {
	if in == nil {
		return nil
	}
	out := new(GuardPluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailRules) DeepCopyInto(out *GuardrailRules) {
	*out = *in
	if in.NemoGuardrails != nil {
		in, out := &in.NemoGuardrails, &out.NemoGuardrails
		*out = new(NemoGuardrailsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InputGuard != nil {
		in, out := &in.InputGuard, &out.InputGuard
		*out = new(GuardPluginConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputGuard != nil {
		in, out := &in.OutputGuard, &out.OutputGuard
		*out = new(GuardPluginConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailRules.
func (in *GuardrailRules) DeepCopy() *GuardrailRules {
	if in == nil {
		return nil
	}
	out := new(GuardrailRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourceRef) DeepCopyInto(out *ManagedResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourceRef.
func (in *ManagedResourceRef) DeepCopy() *ManagedResourceRef {
	if in == nil {
		return nil
	}
	out := new(ManagedResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NemoConfigRef) DeepCopyInto(out *NemoConfigRef) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NemoConfigRef.
func (in *NemoConfigRef) DeepCopy() *NemoConfigRef {
	if in == nil {
		return nil
	}
	out := new(NemoConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NemoGuardrailsConfig) DeepCopyInto(out *NemoGuardrailsConfig) {
	*out = *in
	if in.NemoConfigs != nil {
		in, out := &in.NemoConfigs, &out.NemoConfigs
		*out = make([]NemoConfigRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NemoGuardrailsConfig.
func (in *NemoGuardrailsConfig) DeepCopy() *NemoGuardrailsConfig {
	if in == nil {
		return nil
	}
	out := new(NemoGuardrailsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDefaults) DeepCopyInto(out *PolicyDefaults) {
	*out = *in
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(GuardrailRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDefaults.
func (in *PolicyDefaults) DeepCopy() *PolicyDefaults {
	if in == nil {
		return nil
	}
	out := new(PolicyDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyOverrides) DeepCopyInto(out *PolicyOverrides) {
	*out = *in
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(GuardrailRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyOverrides.
func (in *PolicyOverrides) DeepCopy() *PolicyOverrides {
	if in == nil {
		return nil
	}
	out := new(PolicyOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
