FROM registry.access.redhat.com/ubi8/go-toolset:1.21 AS builder

WORKDIR /go/src/github.com/trustyai-explainability/trustyai-service-operator
COPY . .

RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -tags netgo -ldflags '-extldflags "-static"' -o /bin/driver ./cmd/lmes_driver/*.go

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

COPY --from=builder /bin/driver /bin/driver

USER 65532:65532

WORKDIR /bin

ENTRYPOINT [ "/bin/driver" ]