resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/trustyai/trustyai-service-operator
  newTag: latest
configMapGenerator:
  - name: trustyai-service-operator-config
    files:
      - ./trustyai-service-operator-config.yaml
    options:
      disableNameSuffixHash: true