apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/managed-by: kustomize
  name: lmes-grpc
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    control-plane: controller-manager
