apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-guardrail-policy-manager-role
rules:
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - clusterguardrailpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - clusterguardrailpolicies/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - clusterguardrailpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - nemoguardrails
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - nemoguardrails/status
  verbs:
  - get
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
