apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Orchestrator.Name }}-kube-rbac-proxy-gateway-config
  namespace: {{ .Orchestrator.Namespace }}
  labels:
    app: {{ .Orchestrator.Name }}
    app.kubernetes.io/instance: {{ .Orchestrator.Name }}
    app.kubernetes.io/name: {{ .Orchestrator.Name }}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/component: kube-rbac-proxy
    component: gateway
data:
  config.yaml: |
    authorization:
      resourceAttributes:
        namespace: "{{ .Orchestrator.Namespace }}"
        resource: "services"
        resourceName: "{{ .Orchestrator.Name }}-gateway-service"
        verb: "get"
        apiGroup: ""
    upstreamConfig:
      url: "http://127.0.0.1:8090"
      proxyTimeout: "30s"
    tlsConfig:
      minVersion: "VersionTLS12"
      # FIPS 140-2 approved cipher suites only
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"