releases:
  - name: TrustyAI operator
    version: v1.37.0
    repoUrl: https://github.com/trustyai-explainability/trustyai-service-operator
  - name: TrustyAI service
    version: v0.28.0
    repoUrl: https://github.com/trustyai-explainability/trustyai-explainability
  - name: TrustyAI LMEval driver
    version: v1.37.0
    repoUrl: https://github.com/trustyai-explainability/trustyai-service-operator
  - name: TrustyAI LMEval job
    version: v0.4.8
    repoUrl: https://github.com/EleutherAI/lm-evaluation-harness
  - name: EvalHub
    version: v0.3.0
    repoUrl: https://github.com/eval-hub/eval-hub
