apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/instance: metrics-service
    app.kubernetes.io/created-by: trustyai-service-operator
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/managed-by: kustomize
  name: metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/part-of: trustyai
