apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/instance: service-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: trustyai-service-operator
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/managed-by: kustomize
  name: service-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/part-of: trustyai
