apiVersion: v1
kind: Service
metadata:
  name: {{.Owner.Name}}-service
  namespace: {{.Owner.Namespace}}
  labels:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{.Owner.Name}}-tls
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: oauth-proxy
      protocol: TCP
      port: 443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
