apiVersion: components.platform.opendatahub.io/v1alpha1
kind: TrustyAI
metadata:
  name: default
spec:
  managementState: Managed
  enabledServices:
    tas: true
    lmes: true
    evalHub: true
    gorch: false
    nemoGuardrails: false
