# permissions for end users to view trustyaipipelinemanifest.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: trustyaipipelinemanifest-viewer-role
rules:
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - trustyaipipelinemanifest
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - trustyaipipelinemanifest/status
  verbs:
  - get
