package trustyaimodule

// paramsEnvMap maps each params.env key to the RELATED_IMAGE_* environment
// variable injected by the ODH platform into the module controller pod.
var paramsEnvMap = map[string]string{
	"TRUSTYAI_OPERATOR_IMAGE":                  "RELATED_IMAGE_ODH_TRUSTYAI_OPERATOR_IMAGE",
	"TRUSTYAI_SERVICE_IMAGE":                   "RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_PY_IMAGE",
	"EVAL_HUB_IMAGE":                           "RELATED_IMAGE_ODH_EVAL_HUB_IMAGE",
	"KUBE_RBAC_PROXY_IMAGE":                    "RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE",
	"TA_LMES_JOB_IMAGE":                        "RELATED_IMAGE_ODH_TA_LMES_JOB_IMAGE",
	"TA_LMES_DRIVER_IMAGE":                     "RELATED_IMAGE_ODH_TA_LMES_DRIVER_IMAGE",
	"FMS_GUARDRAILS_ORCHESTRATOR_IMAGE":        "RELATED_IMAGE_ODH_FMS_GUARDRAILS_ORCHESTRATOR_IMAGE",
	"BUILT_IN_DETECTOR_IMAGE":                  "RELATED_IMAGE_ODH_BUILT_IN_DETECTOR_IMAGE",
	"TRUSTYAI_VLLM_ORCHESTRATOR_GATEWAY_IMAGE": "RELATED_IMAGE_ODH_TRUSTYAI_VLLM_ORCHESTRATOR_GATEWAY_IMAGE",
	"TRUSTYAI_GARAK_LLS_PROVIDER_DSP_IMAGE":    "RELATED_IMAGE_ODH_TRUSTYAI_GARAK_LLS_PROVIDER_DSP_IMAGE",
	"TRUSTYAI_NEMO_GUARDRAILS_SERVER_IMAGE":    "RELATED_IMAGE_ODH_TRUSTYAI_NEMO_GUARDRAILS_SERVER_IMAGE",
}
