kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: {{ .Instance.Name }}
  namespace: {{ .Instance.Namespace }}
  labels:
    app: {{ .Instance.Name }}
    app.kubernetes.io/instance: {{ .Instance.Name }}
    app.kubernetes.io/name: {{ .Instance.Name }}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: {{ .Version }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Instance.Name }}
      app.kubernetes.io/instance: {{ .Instance.Name }}
      app.kubernetes.io/name: {{ .Instance.Name }}
      app.kubernetes.io/part-of: trustyai
      app.kubernetes.io/version: {{ .Version }}
  template:
    metadata:
      labels:
        app: {{ .Instance.Name }}
        app.kubernetes.io/instance: {{ .Instance.Name }}
        app.kubernetes.io/name: {{ .Instance.Name }}
        app.kubernetes.io/part-of: trustyai
        app.kubernetes.io/version: {{ .Version }}
      annotations:
        prometheus.io/path: /q/metrics
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: {{ .Instance.Name }}-proxy
      containers:
        - name: trustyai-service
          image: {{ .ServiceImage }}
          env:
            - name: SERVICE_STORAGE_FORMAT
              value: {{ .Instance.Spec.Storage.Format }}
            {{ if eq .Instance.Spec.Storage.Format "PVC" }}
            - name: STORAGE_DATA_FILENAME
              value: {{ .Instance.Spec.Data.Filename }}
            - name: STORAGE_DATA_FOLDER
              value: {{ .Instance.Spec.Storage.Folder }}
            - name: SERVICE_DATA_FORMAT
              value: {{ .Instance.Spec.Data.Format }}
            - name: QUARKUS_HIBERNATE_ORM_ACTIVE
              value: false
            {{ end }}
            {{ if .Instance.IsMigration }}
            - name: STORAGE_DATA_FILENAME
              value: {{ .Instance.Spec.Data.Filename }}
            - name: STORAGE_DATA_FOLDER
              value: {{ .Instance.Spec.Storage.Folder }}
            - name: SERVICE_DATA_FORMAT
              value: {{ .Instance.Spec.Data.Format }}
            {{ end }}
            {{ if eq .Instance.Spec.Storage.Format "DATABASE" }}
            - name: QUARKUS_HIBERNATE_ORM_ACTIVE
              value: true
            - name: QUARKUS_DATASOURCE_DB_KIND
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databaseKind
            - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
              value: 16
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databaseUsername
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databasePassword
            - name: DATABASE_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databaseService
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databasePort
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databaseName
            - name: QUARKUS_DATASOURCE_JDBC_URL
            {{ if .UseDBTLSCerts }}
              value: "jdbc:${QUARKUS_DATASOURCE_DB_KIND}://${DATABASE_SERVICE}:${DATABASE_PORT}/${DATABASE_NAME}?sslMode=verify-ca&serverSslCert=/etc/tls/db/tls.crt"
            {{ else }}
              value: "jdbc:${QUARKUS_DATASOURCE_DB_KIND}://${DATABASE_SERVICE}:${DATABASE_PORT}/${DATABASE_NAME}"
            {{ end }}
            - name: SERVICE_DATA_FORMAT
              value: "HIBERNATE"
            - name: QUARKUS_DATASOURCE_GENERATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Instance.Spec.Storage.DatabaseConfigurations }}
                  key: databaseGeneration
            {{ end }}
            - name: SERVICE_METRICS_SCHEDULE
              value: {{ .Instance.Spec.Metrics.Schedule }}
            - name: SERVICE_BATCH_SIZE
              value: {{ .BatchSize }}
            {{ if .Instance.IsMigration }}
            - name: STORAGE_MIGRATION_CONFIG_FROM_FOLDER
              value: {{ .Instance.Spec.Storage.Folder }}
            - name: STORAGE_MIGRATION_CONFIG_FROM_FILENAME
              value: {{ .Instance.Spec.Data.Filename }}
            {{ end }}
          volumeMounts:
            - name: {{ .Instance.Name }}-internal
              readOnly: false
              mountPath: /etc/tls/internal
            {{ if or (eq .Instance.Spec.Storage.Format "PVC") (.Instance.IsMigration) }}
            - name: {{ .VolumeMountName }}
              mountPath: {{ .Instance.Spec.Storage.Folder }}
              readOnly: false
            {{ end }}
            {{ if .UseDBTLSCerts }}
            - name: db-tls-certs
              mountPath: /etc/tls/db
              readOnly: true
            {{ end }}
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          name: oauth-proxy
          livenessProbe:
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: oauth-proxy
              containerPort: 8443
              protocol: TCP
          volumeMounts:
          {{ if .CustomCertificatesBundle.IsDefined }}
            - name: {{ .CustomCertificatesBundle.VolumeName }}
              readOnly: true
              mountPath: /etc/ssl/certs/ca-bundle.crt
              subPath: ca-bundle.crt
              {{ end }}
            - name: {{ .Instance.Name }}-tls
              mountPath: /etc/tls/private
          image: {{ .OAuthImage }}
          args:
            - '--cookie-secret=SECRET'
            - '--https-address=:8443'
            - '--email-domain=*'
            - '--openshift-service-account={{ .Instance.Name }}-proxy'
            {{ if .CustomCertificatesBundle.IsDefined }}
            - '--openshift-ca=/etc/ssl/certs/ca-bundle.crt'
            {{ end }}
            - '--provider=openshift'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8080'
            - '--skip-auth-regex=''(^/apis/v1beta1/healthz)'''
            - >-
              --openshift-sar={"namespace":"{{ .Instance.Namespace }}","resource":"pods","verb":"get"}
            - >-
              --openshift-delegate-urls={"/": {"namespace": "{{ .Instance.Namespace }}", "resource":
              "pods", "verb": "get"}}
      serviceAccount: {{ .Instance.Name }}-proxy
      volumes:
        {{ if or (eq .Instance.Spec.Storage.Format "PVC") ( .Instance.IsMigration) }}
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .PVCClaimName }}
        {{ end }}
        {{ if .CustomCertificatesBundle.IsDefined }}
        - name: {{ .CustomCertificatesBundle.VolumeName}}
          configMap:
            name: {{ .CustomCertificatesBundle.ConfigMapName }}
            defaultMode: 420
        {{ end }}
        - name: {{ .Instance.Name}}-tls
          secret:
            secretName: {{ .Instance.Name }}-tls
            defaultMode: 420
        - name: {{ .Instance.Name}}-internal
          secret:
            secretName: {{ .Instance.Name }}-internal
            defaultMode: 420
        {{ if .UseDBTLSCerts }}
        - name: db-tls-certs
          secret:
            secretName: {{ .Instance.Name }}-db-tls
            defaultMode: 420
        {{ end }}
