apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        modelmesh-service: modelmesh-serving
    name: {{ .ServiceName }}
    namespace: {{ .Namespace }}
spec:
    endpoints:
        - bearerTokenSecret:
              key: ''
          honorLabels: true
          interval: 4s
          metricRelabelings:
              - action: keep
                regex: trustyai_.*
                sourceLabels:
                    - __name__
          params:
              'match[]':
                  - '{__name__= "trustyai_spd"}'
                  - '{__name__= "trustyai_dir"}'
          path: /q/metrics
          scheme: http
    namespaceSelector:
        any: true
    selector:
        matchLabels:
            app.kubernetes.io/part-of: {{ .ComponentName }}
