kind: Service
apiVersion: v1
metadata:
    annotations:
        service.beta.openshift.io/serving-cert-secret-name: {{ .Owner.Name }}-tls
    name: {{ .Name }}
    namespace: {{ .Namespace }}
    labels:
        app: {{ .Owner.Name }}
        app.kubernetes.io/instance: {{ .Owner.Name }}
        app.kubernetes.io/name: {{ .Owner.Name }}
        app.kubernetes.io/part-of: trustyai
        app.kubernetes.io/version: {{ .Version }}
        trustyai-service-name: {{ .Owner.Name }}
spec:
    ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 8443
    selector:
        app: {{ .Owner.Name }}
