resources:
  - provider-garak.yaml
  - provider-garak-kfp.yaml
  - provider-guidellm.yaml
  - provider-lighteval.yaml
  - provider-lm-evaluation-harness.yaml
  - collection-leaderboard-v2.yaml

namespace: system
