apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Instance.Name }}-kube-rbac-proxy-config
  namespace: {{ .Instance.Namespace }}
  labels:
    app: {{ .Instance.Name }}
    app.kubernetes.io/instance: {{ .Instance.Name }}
    app.kubernetes.io/name: {{ .Instance.Name }}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: {{ .Version }}
    app.kubernetes.io/component: kube-rbac-proxy
data:
  config.yaml: |
    authorization:
      resourceAttributes:
        namespace: "{{ .Instance.Namespace }}"
        resource: "services"
        resourceName: "{{ .Instance.Name }}"
        verb: "get"
        apiGroup: ""
    upstreamConfig:
      url: "http://127.0.0.1:8080"
      proxyTimeout: "30s"
    tlsConfig:
      minVersion: "VersionTLS12"
      # FIPS 140-2 approved cipher suites only
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"