apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trustyai.opendatahub.io_trustyaiservices.yaml
  - trustyai.opendatahub.io_lmevaljobs.yaml
  - trustyai.opendatahub.io_guardrailsorchestrators.yaml
  - trustyai.opendatahub.io_evalhubs.yaml
  - trustyai.opendatahub.io_nemoguardrails.yaml
