kind: Service
apiVersion: v1
metadata:
    annotations:
        service.beta.openshift.io/serving-cert-secret-name: {{ .Instance.Name }}-tls
    name: {{ .Instance.Name }}-tls
    namespace: {{ .Instance.Namespace }}
    labels:
        app: {{ .Instance.Name }}
        app.kubernetes.io/instance: {{ .Instance.Name }}
        app.kubernetes.io/name: {{ .Instance.Name }}
        app.kubernetes.io/part-of: trustyai
        app.kubernetes.io/version: 0.1.0
        trustyai-service-name: {{ .Instance.Name }}
spec:
    ports:
        - name: oauth-proxy
          protocol: TCP
          port: 443
          targetPort: 8443
    selector:
        app: {{ .Instance.Name }}