kind: Service
apiVersion: v1
metadata:
    annotations:
        prometheus.io/path: /q/metrics
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
    name: {{ .Name }}
    namespace: {{ .Namespace }}
    labels:
        app: {{ .Name }}
        app.kubernetes.io/instance: {{ .Name }}
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/part-of: trustyai
        app.kubernetes.io/version: {{ .Version }}
spec:
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
        - name: http-event
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: https
          protocol: TCP
          port: 443
          targetPort: 4443
    type: ClusterIP
    selector:
        app: {{ .Name }}
        app.kubernetes.io/instance: {{ .Name }}
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/part-of: trustyai
        app.kubernetes.io/version: {{ .Version }}
