resources:
  - bases/trustyai.opendatahub.io_trustyaiservices.yaml
  - bases/trustyai.opendatahub.io_lmevaljobs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
#+kubebuilder:scaffold:crdkustomizewebhookpatch
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
  - kustomizeconfig.yaml
