apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustyai-operator
  namespace: trustyai-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: trustyai-operator
  template:
    metadata:
      labels:
        control-plane: trustyai-operator
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: trustyai-operator
          image: quay.io/trustyai/trustyai-service-operator:latest
          imagePullPolicy: Always
          command:
            - /manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080