// Copyright 2024.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: controllers/lmes/api/v1beta1/update_status.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LMEvalJobUpdateServiceClient is the client API for LMEvalJobUpdateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LMEvalJobUpdateServiceClient interface {
	UpdateStatus(ctx context.Context, in *JobStatus, opts ...grpc.CallOption) (*Response, error)
}

type lMEvalJobUpdateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLMEvalJobUpdateServiceClient(cc grpc.ClientConnInterface) LMEvalJobUpdateServiceClient {
	return &lMEvalJobUpdateServiceClient{cc}
}

func (c *lMEvalJobUpdateServiceClient) UpdateStatus(ctx context.Context, in *JobStatus, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/LMEvalJobUpdateService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LMEvalJobUpdateServiceServer is the server API for LMEvalJobUpdateService service.
// All implementations must embed UnimplementedLMEvalJobUpdateServiceServer
// for forward compatibility
type LMEvalJobUpdateServiceServer interface {
	UpdateStatus(context.Context, *JobStatus) (*Response, error)
	mustEmbedUnimplementedLMEvalJobUpdateServiceServer()
}

// UnimplementedLMEvalJobUpdateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLMEvalJobUpdateServiceServer struct {
}

func (UnimplementedLMEvalJobUpdateServiceServer) UpdateStatus(context.Context, *JobStatus) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedLMEvalJobUpdateServiceServer) mustEmbedUnimplementedLMEvalJobUpdateServiceServer() {
}

// UnsafeLMEvalJobUpdateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LMEvalJobUpdateServiceServer will
// result in compilation errors.
type UnsafeLMEvalJobUpdateServiceServer interface {
	mustEmbedUnimplementedLMEvalJobUpdateServiceServer()
}

func RegisterLMEvalJobUpdateServiceServer(s grpc.ServiceRegistrar, srv LMEvalJobUpdateServiceServer) {
	s.RegisterService(&LMEvalJobUpdateService_ServiceDesc, srv)
}

func _LMEvalJobUpdateService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LMEvalJobUpdateServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LMEvalJobUpdateService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LMEvalJobUpdateServiceServer).UpdateStatus(ctx, req.(*JobStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// LMEvalJobUpdateService_ServiceDesc is the grpc.ServiceDesc for LMEvalJobUpdateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LMEvalJobUpdateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LMEvalJobUpdateService",
	HandlerType: (*LMEvalJobUpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStatus",
			Handler:    _LMEvalJobUpdateService_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/api/v1beta1/update_status.proto",
}
