apiVersion: v1
kind: Service
metadata:
  name: {{.Orchestrator.Name}}-service
  namespace: {{.Orchestrator.Namespace}}
  labels:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
spec:
  ipFamilies:
    - IPv4
  ports:
    {{if .Orchestrator.Spec.EnableGuardrailsGateway}}
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
    {{else}}
    - name: http
      protocol: TCP
      port: 8033
      targetPort: 8033
    {{end}}
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
