apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Owner.Name }}-tls
  labels:
    app: {{.Owner.Name}}
    component: {{ .Owner.Name }}

spec:
  ipFamilies:
    - IPv4
  ports:
    {{if .Owner.Spec.EnableGuardrailsGateway}}
    - name: gateway
      protocol: TCP
      port: {{if .UseAuthProxy}}8490{{else}}8090{{end}}
      targetPort: {{if .UseAuthProxy}}8490{{else}}8090{{end}}
    {{end -}}
    {{if not .Owner.Spec.DisableOrchestrator }}
    - name: https
      protocol: TCP
      port: {{if .UseAuthProxy}}8432{{else}}8032{{end}}
      targetPort: {{if .UseAuthProxy}}8432{{else}}8032{{end}}
    {{if .UseAuthProxy}}
    - name: https-tls
      protocol: TCP
      port: 8032
      targetPort: 8032
    {{end}}
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
    {{end}}
    {{if .Owner.Spec.EnableBuiltInDetectors}}
    {{if .UseAuthProxy}}
    - name: built-in-detector-metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    {{end}}
    - name: built-in-detector
      protocol: TCP
      port: {{if .UseAuthProxy}}8480{{else}}8080{{end}}
      targetPort: {{if .UseAuthProxy}}8480{{else}}8080{{end}}
    {{end}}
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
